spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  #        use_sql_comments: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/short_url
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
#      springframework:
#        web: info

decorator:
  datasource:
    p6spy:
      enable-logging: true