jpa:
  hibernate:
    ddl-auto: none

logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short-url?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: test
#    url: jdbc:mysql://short-url-rds.cvtvkudd7w9f.ap-northeast-2.rds.amazonaws.com:3306/short_url?serverTimezone=UTC&characterEncoding=UTF-8
#    username: admin
#    password: testtest
  main:
    allow-bean-definition-overriding=true: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true